
# global constants
W : 13.5e-3 #[keV]
g1 : 0.11488 #0.1115 #0.1167 #0.108 #[phd/ph]
g2 : 46.38 #45.67 #43.56 #40.4 #[phd/e-]
SEsize : 57.62 #56.23 #60.17 #[phd]
alpha : 11.43
beta : 1.068
S2thr_upper : 5 #logcS2
S2thr_lower : 2.5 #2.52 #logcS2; 5.5*SEsize 
FVz_upper : 86 #[us]
FVz_lower : 936.5 #[us]
#ER_band_file : '/global/cfs/cdirs/lz/users/grischbi/CommissioningBands/v3/beta_8kV_logS2_skew_band.txt'
#NR_band_file : '/global/cfs/cdirs/lz/users/grischbi/CommissioningBands/v3/flatNR_8kV_logS2_skew_band.txt'
ER_band_file : '/global/cfs/cdirs/lz/physics/NEST_Bands/SR1/20220511/Flat/beta_SR1_logS2_skew_band.txt'
NR_band_file : '/global/cfs/cdirs/lz/physics/NEST_Bands/SR1/20220511/Flat/flatNR_SR1_logS2_skew_band.txt'

# input file
# can be overriden from command line
hist_file : '/global/cfs/cdirs/lz/users/afan/ana/lz/54-SR1/run/SR1WS/SR1WSAnalysis.root'
#hist_file : '/global/cfs/cdirs/lz/users/afan/ana/lz/54-SR1/run/SR1WS/SR1WSAnalysis_SR1-WSv3_LZAP-5.4.5_v15.root'

# can be overriden from command line 
output_folder : 'test'


CH3T_file1 : '/global/cfs/cdirs/lz/users/afan/ana/lz/54-SR1/run/SR1WS/SR1WSAnalysis_CH3T_LZAP-5.4.5_v1.root'
CH3T_file2 : '/global/cfs/cdirs/lz/users/afan/ana/lz/54-SR1/run/SR1WS/SR1WSAnalysis_CH3T_LZAP-5.4.6_v1.root'

# List of cuts. 
# Must be in same order as in SR1WS 
cut_list : [
    'HSX',        #  1
    'MUONVETO',   #  2
    'ETV',        #  3
    'S1RATE',     #  4
    'SS',         #  5
    'ABOVEANODE', #  6
    'GATE',       #  7
    'CATH',       #  8    
    'SSWINDOW',   #  9
    'BUFF',       # 10 
    'BURST',      # 11
    'EXCESSAREA', # 12
    'SUSTPHRATE', # 13
    'S2WIDTH',    # 14
    'NARROWS2',   # 15
    'S2PEAKTIME', # 16
    'XYQUAL',     # 17
    'S2TBA',      # 18
    'S1PROM',     # 19
    'STINGER',    # 20
    'S1TBA',      # 21
    'HSC',        # 22
    'S1SHAPE',    # 23
    'S1CHTIMING', # 24
    'FCRES',      # 25
    'S2THR',      # 26
    'SKINVPROMPT',  # 27
    'SKINVDELAYED', # 28
    'ODVPROMPT',    # 29
    'ODVDELAYED',   # 30
  ]
